require_relative 'includes/bot_regex'
require_relative 'includes/string_monkeypatch'

require_relative 'services/sonos_service'
require_relative 'services/spotify_service'
require_relative 'services/tune_in_service'

require_relative 'commands/what_is_playing'
require_relative 'commands/find_music'
require_relative 'commands/play_music'
require_relative 'commands/next_music'
require_relative 'commands/queue_music'
require_relative 'commands/single_commands'
require_relative 'commands/find_radio'
require_relative 'commands/play_radio'
require_relative 'commands/join_group'
require_relative 'commands/leave_group'
require_relative 'commands/change_group_volume'
require_relative 'commands/change_room_volume'
require_relative 'commands/change_room'
require_relative 'commands/say'
